### ISSUE TITLE
Adding a function of language region conversion

### ISSUE THREAD

**Issue by sammo3182** [sammo3182/regioncode#25]
Converting prefectures and provinces to language zones according to the 1986 or later language data

**Comment by already-love** [comment]
这里出现了一个bug，
bind_cols(region_sname2, region_name2, region_code2, region_language)
region_language这个变量没有定义，不知道这里是想选择表格里的prov_language还是pref_language还是这几种都选择？
以及更新后的master里面表格多了一列area，下次更新先复制一下新master

**Comment by Zhumeng-gif** [comment]
> 这里出现了一个bug，
> bind_cols(region_sname2, region_name2, region_code2, region_language)
> region_language这个变量没有定义，不知道这里是想选择表格里的prov_language还是pref_language还是这几种都选择？
> 以及更新后的master里面表格多了一列area，下次更新先复制一下新master

1. region_language已经删去；2. 以后更新先copy新的master，谢谢你的提醒咩~~

**Comment by sammo3182** [comment]
> 下次更新先复制一下新mast

不是复制，是pull，要养成先pull后push的好习惯 @Zhumeng-gif @already-love

**Comment by already-love** [comment]
> > 下次更新先复制一下新mast
> 
> 不是复制，是pull，要养成先pull后push的好习惯 @Zhumeng-gif @already-love

我一时间忘了pull这个词怎么说了sos说得好！

**Comment by Zhumeng-gif** [comment]
好的，认真学习我导儿5.4日的讲话精神




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月4日(星期二) 晚上7:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sammo3182/regioncode] Adding a function of language region conversion (#25)





   
下次更新先复制一下新mast
  
不是复制，是pull，要养成先pull后push的好习惯 @Zhumeng-gif @already-love
  
我一时间忘了pull这个词怎么说了sos说得好！

**Comment by GohUnTsuan** [comment]
Thanks Zhumeng. I ran the function `language region conversion` using vignette data and found some bugs.

1. Between line 94 to line 134,  if I use method `abbre2name` or "abbre2code" or "abbre2area",  I will get an error message that 'Column `prov_name_nickname` doesn't exist.' 

```     
      year_from <- ifelse(year_from < 1999, 1998, 1999)
      year_to <- ifelse(year_to < 1999, 1998, 1999)
      
      if (is.numeric(data_input))
        year_from <- "prov_code"
      if (is.character(data_input))
        year_from <- "prov_name"
      
      ls_index <- switch (
        method,
        "abbre2name" = {
          year_from <- paste0(year_from, "_nickname")
          year_to <- "prov_name"
          c(year_from, year_to)
        },
        "abbre2code" = {
          year_from <- paste0(year_from, "_nickname")
          year_to <- "prov_code"
          c(year_from, year_to)
        },
        "abbre2area" = {
          year_from <- paste0(year_from, "_nickname")
          year_to <- "area"
          c(year_from, year_to)
        }
      )
```

2. I think param `language_zone` is not necessary. Maybe you can write this function like `incompleteName`.  it means that the default value of param `language_trans`  is none, which means FALSE.
> #' @param incompleteName A character to specify if a short name of region is used. See the Details for more information. The default is "none". Other options are "from", "to", and "both". The default value is "none".

3.  Line 142 to Line152 will get an error message when  `data_input` value are codes (行政编码).
```
regioncode(data_input = vignette_data$prefecture_id, method = '2name', province = FALSE,year_from = 2019,year_to = 1999, language_zone = TRUE, language_trans = 'dia_group')
```
>  Error: Can't join on `x$2019_name` x `y$2019_name` because of incompatible types.
>  i `x$2019_name` is of type <double>>.
>  i `y$2019_name` is of type <character>>.
 I think you should add a function like line 156 to 160 before running pref language_trans.
```
      # when doing prefectural level converting
      if (is.numeric(data_input))
        year_from <- paste0(year_from, '_code')
      if (is.character(data_input))
        year_from <- paste0(year_from, '_name')
```
4. in our project, 'pref' means prefecture-level city(地级市). Variable  'pref_language' in region _table sounds like prefecture-level city's language, but actually, it seems to mean region's language. For example, in row '揭阳市', 'pref_language' is `闽南区` not '揭阳区'.  

@Zhumeng-gif

**Comment by sammo3182** [comment]
Please have a check @Zhumeng-gif

**Comment by Zhumeng-gif** [comment]
Thanks for WQgg's suggestion,I will&nbsp;I will check it as soon as possible！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 凌晨1:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sammo3182/regioncode] Adding a function of language region conversion (#25)





 
Thanks Zhumeng. I ran the function language region conversion using vignette data and found some bugs.
  
Between line 94 to line 134,  if I use method abbre2name or "abbre2code" or "abbre2area",  I will get an error message that 'Column prov_name_nickname doesn't exist.'
        year_from <- ifelse(year_from < 1999, 1998, 1999)       year_to <- ifelse(year_to < 1999, 1998, 1999)              if (is.numeric(data_input))         year_from <- "prov_code"       if (is.character(data_input))         year_from <- "prov_name"              ls_index <- switch (         method,         "abbre2name" = {           year_from <- paste0(year_from, "_nickname")           year_to <- "prov_name"           c(year_from, year_to)         },         "abbre2code" = {           year_from <- paste0(year_from, "_nickname")           year_to <- "prov_code"           c(year_from, year_to)         },         "abbre2area" = {           year_from <- paste0(year_from, "_nickname")           year_to <- "area"           c(year_from, year_to)         }       )   
I think param language_zone is not necessary. Maybe you can write this function like incompleteName.  it means that the default value of param language_trans  is none, which means FALSE.
   
#' @param incompleteName A character to specify if a short name of region is used. See the Details for more information. The default is "none". Other options are "from", "to", and "both". The default value is "none".
   
Line 142 to Line152 will get an error message when  data_input value are codes (行政编码).
  regioncode(data_input = vignette_data$prefecture_id, method = '2name', province = FALSE,year_from = 2019,year_to = 1999, language_zone = TRUE, language_trans = 'dia_group')   
Error: Can't join on x$2019_name x y$2019_name because of incompatible types.
 i x$2019_name is of type &gt;.
 i y$2019_name is of type &gt;.
 I think you should add a function like line 156 to 160 before running pref language_trans.
        # when doing prefectural level converting       if (is.numeric(data_input))         year_from <- paste0(year_from, '_code')       if (is.character(data_input))         year_from <- paste0(year_from, '_name')   
in our project, 'pref' means prefecture-level city(地级市). Variable  'pref_language' in region _table sounds like prefecture-level city's language, but actually, it seems to mean region's language. For example, in row '揭阳市', 'pref_language' is 闽南区 not '揭阳区'.
  
@Zhumeng-gif

**Comment by Zhumeng-gif** [comment]
I will check it as soon as possible~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yue ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 上午6:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sammo3182/regioncode] Adding a function of language region conversion (#25)





 
Please have a check @Zhumeng-gif
